<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U5UN98U" failures="0" tests="1" name="testclasses.TestingTest" time="1.026" errors="1" timestamp="2022-05-03T14:00:23 GMT-04:00" skipped="0">
  <testcase classname="testclasses.TestingTest" name="test1Test" time="1.026">
    <error message="Method testclasses.TestingTest.test1Test() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testclasses.TestingTest.test1Test() didn't finish within the time-out 1000
at java.base@17/java.lang.Thread.sleep(Native Method)
at app//testclasses.TestingTest.test1Test(TestingTest.java:12)
at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:10)
at java.base@17/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- test1Test -->
  <system-out/>
</testsuite> <!-- testclasses.TestingTest -->
