<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U5UN98U" failures="0" tests="1" name="testclasses.Testing" time="1.027" errors="1" timestamp="2022-05-03T13:46:53 GMT-04:00" skipped="0">
  <testcase classname="testclasses.Testing" name="test1" time="1.027">
    <error message="Method testclasses.Testing.test1() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testclasses.Testing.test1() didn't finish within the time-out 1000
at java.base@17/java.lang.Thread.sleep(Native Method)
at app//testclasses.Testing.test1(Testing.java:13)
at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:10)
at java.base@17/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- test1 -->
  <system-out>
    <![CDATA[test case is starting]]>
  </system-out>
</testsuite> <!-- testclasses.Testing -->
